from pydantic import BaseModel, Field
from typing import Optional, List, Dict, Any

class QueryRequest(BaseModel):
    question: str = Field(..., description="The user's question about the tickets.")

class QueryResponse(BaseModel):
    query_type: str = Field(..., description="The classified type of the query: SQL_ANALYTICS or SEMANTIC_SEARCH")
    response: str = Field(..., description="The explanation or answer generated by the AI.")
    raw_data: Optional[List[Any]] = Field(None, description="The raw data rows or tickets retrieved, if applicable.")
    sql_query: Optional[str] = Field(None, description="The executed SQL query, if applicable.")

class IngestResponse(BaseModel):
    status: str = Field(..., description="Success or failure status.")
    message: str = Field(..., description="Detailed message about ingestion process.")
    tickets_ingested: Optional[int] = Field(None, description="Number of tickets ingested during the run.")
